--Friendlist for Azzy AI
--Automatically generated by Azzy AI.
--To add friends, put mercenary or homun into standby mode (ctl+T or alt+T as appropriate), and sit 1 cell to the west (to left in default view) of the person who you wish to friend
--To remove friends, put merc/homun into standby mode, and sit 1 cell to the east (to right in default view) of the person you want to remove.
--
--To add KOS/Enemy/Etc lists, get the ID number from ROPD or by friending them, and make a line like
--MyFriends{2322797}=KOS
--Possible values are NEUTRAL, KOS (kill on sight), ENEMY (assume hostile, but don't attack), and ALLY (assume friendly).
MyFriends={}
MyFriends[1529417]=1 -- Azzy's alt account

-- Ids vary from monster to monster. so. thos doesnt work
-- green  109929330
-- blue - 110029222
-- Plants List - for avoiding if nesessery

PlantsList={}
PlantsList[110020967]=1 -- Red Mushroom
PlantsList[109922154]=1 -- Possible green plant?

function IsPlant(id)
    if (PlantsList[id]~=nil) then
        return 1
    end
    return 0
end
